### ISSUE TITLE
Sources do not compile on Debian

### ISSUE THREAD

**Issue by mwarning** [mbenkmann/netcat-openbsd#1]
Hi,

I was looking for some up to date netcat-openbsd repsoitory.
But the master branch gives me:

```
$ make
Makefile:6: *** missing separator (did you mean TAB instead of 8 spaces?).  Stop.
```

The lhm branch clearly is not intended for other systems as *BSD because of the bsd/ includes.
While the original netcat-openbsd does compile fine on Debian.

**Comment by mbenkmann** [comment]
The build of the lhm branch works fine on Ubuntu trusty using

dpkg-buildpackage -rfakeroot -sa

The bsd/ includes are satisfied by the package libbsd-dev and dpkg-buildpackage tells you about that.
