### ISSUE TITLE
why netcat not working??

### ISSUE THREAD

**Issue by ikelirawan** [mbenkmann/netcat-openbsd#3]
Why syntax
nc -lvp 4444 
nc: protocol not avaliable
Please help me why my netcat not run?

**Comment by mbenkmann** [comment]
You are apparently not using the nc compiled from this github repository, because that one does not produce this message if called that way. So I can't help you.

**Comment by mbenkmann** [comment]
In case there's confusion. I am maintaining ONLY the "lhm" branch.
